version: '2.4'
services:
  web:
    env_file:
      - .env
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    user: $UID:$GID
    ports:
      - "8081:8081"
    volumes:
      - ${PWD}:/var/www
    working_dir: /var/www
    command: php -S 0.0.0.0:8081 public/index.php
    depends_on: 
      - db
  db:
    env_file:
      - .env
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3390:3306"